# Generated by Django 6.0.4 on 2026-04-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOEApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('AJEER', 'Ajeer Registration'), ('SAUDI_EMP', 'Saudi Employee Registration'), ('TEACHER_LICENSE', 'Teacher License (MOE)'), ('IQAMA_RENEWAL', 'Iqama Renewal'), ('WORK_PERMIT', 'Work Permit'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='moe_files/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moe_approvals_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moe_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOE / Regulatory Approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='e.g. EMP-0001', max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('TEACHER', 'Teacher'), ('SENIOR_TEACHER', 'Senior Teacher'), ('HEAD_OF_DEPT', 'Head of Department'), ('COORDINATOR', 'Coordinator'), ('VICE_PRINCIPAL', 'Vice Principal'), ('PRINCIPAL', 'Principal'), ('ACCOUNTANT', 'Accountant'), ('HR_OFFICER', 'HR Officer'), ('IT_OFFICER', 'IT Officer'), ('COUNSELOR', 'Counselor'), ('LIBRARIAN', 'Librarian'), ('SECURITY_GUARD', 'Security Guard'), ('DRIVER', 'Driver'), ('CLERK', 'Clerk'), ('OTHER', 'Other')], max_length=30)),
                ('department', models.CharField(choices=[('ACADEMIC', 'Academic'), ('ADMIN', 'Administration'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('OPERATIONS', 'Operations'), ('HR', 'Human Resources'), ('SECURITY', 'Security'), ('TRANSPORT', 'Transport'), ('COUNSELING', 'Counseling'), ('OTHER', 'Other')], max_length=20)),
                ('join_date', models.DateField()),
                ('nationality', models.CharField(default='Saudi', max_length=60)),
                ('iqama_number', models.CharField(blank=True, help_text='For foreign employees', max_length=20)),
                ('iqama_expiry', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('SAUDI', 'Saudi National'), ('FOREIGN', 'Foreign (Expatriate)')], default='FOREIGN', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.division')),
                ('subjects_taught', models.ManyToManyField(blank=True, help_text='Subjects this staff member is qualified to teach', related_name='teaching_staff', to='core.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'ordering': ['department', 'user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('vacation_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('HAJJ', 'Hajj Leave'), ('MATERNITY', 'Maternity / Paternity Leave'), ('UNPAID', 'Unpaid Leave')], default='ANNUAL', max_length=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_approvals', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacation Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'ordering': ['academic_year', 'section', 'subject'],
                'unique_together': {('teacher', 'subject', 'section', 'academic_year')},
            },
        ),
    ]
