# Generated by Django 6.0.4 on 2026-04-13 11:33

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name (English)')),
                ('arabic_name', models.CharField(max_length=200, verbose_name='الاسم الكامل (عربي)')),
                ('dob', models.DateField(verbose_name='Date of Birth / تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'Male / ذكر'), ('F', 'Female / أنثى')], max_length=1, verbose_name='Gender / الجنس')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality / الجنسية')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='National ID / الهوية الوطنية')),
                ('roll_number', models.CharField(blank=True, max_length=10, verbose_name='Roll No. / رقم السجل')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name="Father's Name / اسم الأب")),
                ('arabic_father', models.CharField(blank=True, max_length=200, verbose_name='اسم الأب (عربي)')),
                ('mother_name', models.CharField(blank=True, max_length=200, verbose_name="Mother's Name / اسم الأم")),
                ('arabic_mother', models.CharField(blank=True, max_length=200, verbose_name='اسم الأم (عربي)')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Guardian Phone / هاتف ولي الأمر')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Guardian Email / بريد ولي الأمر')),
                ('guardian_phone2', models.CharField(blank=True, max_length=20, verbose_name='Alt. Phone / هاتف بديل')),
                ('address', models.TextField(blank=True, verbose_name='Address / العنوان')),
                ('arabic_address', models.TextField(blank=True, verbose_name='العنوان (عربي)')),
                ('enrollment_type', models.CharField(choices=[('NEW', 'New Student / طالب جديد'), ('TRANSFER', 'Transfer / منقول'), ('RETURNING', 'Returning / عائد')], default='NEW', max_length=15, verbose_name='Enrollment Type / نوع القيد')),
                ('admission_date', models.DateField(verbose_name='Admission Date / تاريخ القبول')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / نشط')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School / المدرسة السابقة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='Photo / الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.academicyear', verbose_name='Academic Year / السنة الدراسية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_added', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.division', verbose_name='Division / القسم')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.grade', verbose_name='Grade / الصف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.section', verbose_name='Section / الفصل')),
            ],
            options={
                'verbose_name': 'Student / طالب',
                'ordering': ['grade', 'section', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport / جواز السفر'), ('NATIONAL_ID', 'National ID / الهوية الوطنية'), ('BIRTH_CERT', 'Birth Certificate / شهادة الميلاد'), ('TRANSFER_CERT', 'Transfer Certificate / شهادة النقل'), ('PHOTO', 'Photograph / صورة شخصية'), ('OTHER', 'Other / أخرى')], max_length=20, verbose_name='Document Type / نوع الوثيقة')),
                ('file', models.FileField(upload_to=students.models.student_doc_path, verbose_name='File / الملف')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Notes / ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document / وثيقة الطالب',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
