# Generated by Django 6.0.4 on 2026-04-13 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section'], name='student_section_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'section'], name='student_grade_section_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year', 'is_active'], name='student_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='student_id_idx'),
        ),
    ]
