# Generated by Django 6.0.4 on 2026-04-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentdocument_iqama_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name="Father's ID / هوية الأب"),
        ),
    ]
