# Generated by Django 6.0.4 on 2026-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_father_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_business_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Father Business Phone / رقم هاتف العمل'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Father Email / البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_employed_at_school',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Father Employed at Al Kawthar? / الوالد عضو في هيئة التدريس؟'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_employer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Company Name / اسم الشركة'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_family_book_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Father Family Book No. (Saudi) / رقم دفتر العائلة'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_home_address',
            field=models.TextField(blank=True, verbose_name='Father Home Address / عنوان المنزل'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Father Home Phone / رقم هاتف المنزل'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Father Mobile / رقم الجوال'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Father Nationality / الجنسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Occupation / المهنة'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_school_job',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father School Job / تحديد الوظيفة'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_work_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Father Work Address / عنوان العمل'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_business_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mother Business Phone / رقم هاتف العمل'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Mother Email / البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_employed_at_school',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Mother Employed at Al Kawthar? / الأم عضو في هيئة التدريس؟'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_employer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Company Name / اسم الشركة'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_family_book_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mother Family Book No. (Saudi) / رقم دفتر العائلة'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_home_address',
            field=models.TextField(blank=True, verbose_name='Mother Home Address / عنوان المنزل'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mother Home Phone / رقم هاتف المنزل'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mother Mobile / رقم الجوال'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mother ID/Iqama Number / رقم الإقامة للجنسية الأجنبية'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mother Nationality / الجنسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Occupation / المهنة'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_school_job',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother School Job / تحديد الوظيفة'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_work_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mother Work Address / عنوان العمل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='arabic_father',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Full Name (Arabic) / الاسم بالكامل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='arabic_mother',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Full Name (Arabic) / الاسم بالكامل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Full Name (Latin) / الاسم بالكامل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Father ID/Iqama Number / رقم الإقامة للجنسية الأجنبية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Full Name (Latin) / الاسم بالكامل'),
        ),
    ]
