# Generated by Django 6.0.4 on 2026-04-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_father_mother_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name / الاسم بالكامل')),
                ('relation', models.CharField(choices=[('BROTHER', 'Brother / أخ'), ('SISTER', 'Sister / أخت')], max_length=10, verbose_name='Relation / العلاقة')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth / تاريخ الميلاد')),
                ('current_school', models.CharField(blank=True, max_length=200, verbose_name='Current School / المدرسة الحالية')),
                ('educational_level', models.CharField(blank=True, max_length=200, verbose_name='Educational Level / المرحلة الدراسية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='students.student')),
            ],
            options={
                'verbose_name': 'Sibling / أخ/أخت',
                'ordering': ['relation', 'full_name'],
            },
        ),
    ]
