# Generated by Django 6.0.4 on 2026-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_sibling_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Birth Place / مكان الميلاد'),
        ),
        migrations.AddField(
            model_name='student',
            name='iqama_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Iqama Number / رقم الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Passport Number / رقم جواز السفر'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Religion / الديانة'),
        ),
    ]
