# Generated by Django 6.0.4 on 2026-04-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_iqama_passport_religion_birthplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name / الاسم بالكامل')),
                ('relation', models.CharField(max_length=100, verbose_name='Relation / العلاقة')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone / رقم الهاتف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='students.student')),
            ],
            options={
                'verbose_name': 'Authorized Pickup Person / شخص مُصرَّح له باصطحاب الطالب',
                'ordering': ['full_name'],
            },
        ),
    ]
