# Generated by Django 6.0.4 on 2026-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_add_authorized_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_category',
            field=models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('other', 'Other')], default='regular', help_text='Determines which fee structure applies to this student', max_length=10, verbose_name='Fee Category'),
        ),
    ]
