# Generated by Django 6.0.4 on 2026-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_fee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_type',
            field=models.CharField(choices=[('NEW', 'New Student / طالب جديد'), ('TRANSFER', 'Transfer / منقول'), ('REGULAR', 'Regular (Continuing) / مستمر')], default='NEW', max_length=15, verbose_name='Enrollment Type / نوع القيد'),
        ),
    ]
