# Generated by Django 6.0.4 on 2026-05-06 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studymode'),
        ('students', '0011_alter_student_enrollment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_mode',
            field=models.ForeignKey(blank=True, help_text='Required for Regular (continuing) students; choose how they study.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.studymode', verbose_name='Study Mode / نمط الدراسة'),
        ),
    ]
