# Generated by Django 6.0.4 on 2026-05-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_study_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_category',
            field=models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('transfer', 'Transfer'), ('other', 'Other')], default='regular', help_text='Determines which fee structure applies to this student', max_length=10, verbose_name='Fee Category'),
        ),
    ]
