# Generated by Django 6.0.4 on 2026-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_fee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim / مسلم'), ('Non-Muslim', 'Non-Muslim / غير مسلم')], max_length=20, verbose_name='Religion / الديانة'),
        ),
    ]
