# Generated by Django 6.0.4 on 2026-04-13 12:23

import django.db.models.deletion
import django.utils.timezone
import fees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TUITION', 'Tuition / رسوم دراسية'), ('TRANSPORT', 'Transport / مواصلات'), ('UNIFORM', 'Uniform / زي مدرسي'), ('BOOKS', 'Books & Supplies / كتب ومستلزمات'), ('EXTRACURRICULAR', 'Extracurricular / أنشطة'), ('OTHER', 'Other / أخرى')], default='OTHER', max_length=20)),
                ('is_taxable', models.BooleanField(default=False, help_text='Subject to 15% VAT (ZATCA)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(help_text='Deadline for payment')),
                ('frequency', models.CharField(choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('TERM', 'Per Term'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.academicyear')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.division')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.grade')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='fees.feetype')),
            ],
            options={
                'ordering': ['grade', 'fee_type'],
                'unique_together': {('academic_year', 'grade', 'division', 'fee_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base amount (copied from structure)', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in SAR', max_digits=10)),
                ('discount_note', models.CharField(blank=True, max_length=200)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='amount − discount + tax', max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid / غير مدفوع'), ('PARTIAL', 'Partial / مدفوع جزئيًا'), ('PAID', 'Paid / مدفوع'), ('OVERDUE', 'Overdue / متأخر'), ('WAIVED', 'Waived / معفى')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_assigned', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
            options={
                'ordering': ['due_date', 'student'],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash / نقدًا'), ('BANK', 'Bank Transfer / تحويل بنكي'), ('MADA', 'Mada / مدى'), ('ONLINE', 'Online / إلكتروني'), ('CHEQUE', 'Cheque / شيك')], default='CASH', max_length=10)),
                ('receipt_number', models.CharField(default=fees.models._receipt_number, editable=False, max_length=30, unique=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='Bank ref / cheque no.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=fees.models._invoice_number, editable=False, max_length=40, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('line_items_json', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month (e.g. 2025-09-01)')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Housing Allowance')),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Transport Allowance')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Absences / penalties', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('bank_ref', models.CharField(blank=True, max_length=100, verbose_name='Bank Transfer Ref')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER', 'ACCOUNTANT', 'STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
