# Generated by Django 6.0.4 on 2026-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_verified',
            field=models.BooleanField(default=False, help_text='Confirmed against bank statement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('STANDARD', 'Tax Invoice / فاتورة ضريبية'), ('CREDIT_NOTE', 'Tax Credit Note / إشعار دائن ضريبي')], default='STANDARD', max_length=15),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='category',
            field=models.CharField(choices=[('TUITION', 'Tuition / رسوم دراسية'), ('TRANSPORT', 'Transport / مواصلات'), ('UNIFORM', 'Uniform / زي مدرسي'), ('BOOKS', 'Books & Supplies / كتب ومستلزمات'), ('EXTRACURRICULAR', 'Extracurricular / أنشطة'), ('RESERVATION', 'Reservation / حجز مقعد'), ('ENTRANCE_EXAM', 'Entrance Exam / اختبار قبول'), ('OTHER', 'Other / أخرى')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOIDED', 'Voided'), ('CREDIT_NOTE', 'Credit Note / إشعار دائن')], default='DRAFT', max_length=15),
        ),
    ]
