# Generated by Django 6.0.4 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_fees_invoice_creditnote_bankverify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['grade__name', 'fee_type__name']},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['due_date', 'student__full_name']},
        ),
        migrations.AlterField(
            model_name='feetype',
            name='category',
            field=models.CharField(choices=[('TUITION', 'Tuition / رسوم دراسية'), ('ADMISSION', 'Admission Fee / رسوم القبول'), ('REGISTRATION', 'Registration Fee / رسوم التسجيل'), ('EXAMINATION', 'Examination Fee / رسوم الامتحان'), ('TRANSPORT', 'Transport / مواصلات'), ('UNIFORM', 'Uniform / زي مدرسي'), ('BOOKS', 'Books & Supplies / كتب ومستلزمات'), ('EXTRACURRICULAR', 'Extracurricular / أنشطة'), ('LIBRARY', 'Library Fee / رسوم المكتبة'), ('LABORATORY', 'Laboratory Fee / رسوم المختبر'), ('SPORTS', 'Sports Fee / رسوم الرياضة'), ('ANNUAL_FUNCTION', 'Annual Function Fee / رسوم الحفل السنوي'), ('DEVELOPMENT', 'Development Fee / رسوم التطوير'), ('SMART_CLASS', 'Smart Class / IT Fee / رسوم الفصل الذكي'), ('ID_CARD', 'ID Card Fee / رسوم البطاقة'), ('SECURITY_DEPOSIT', 'Security Deposit (Refundable) / تأمين'), ('HOSTEL', 'Hostel Fee / رسوم السكن'), ('MESS', 'Mess / Food Fee / رسوم الطعام'), ('LATE_FEE', 'Late Fee / Fine / غرامة تأخير'), ('RESERVATION', 'Reservation / حجز مقعد'), ('ENTRANCE_EXAM', 'Entrance Exam / اختبار قبول'), ('OTHER', 'Other / أخرى')], default='OTHER', max_length=20),
        ),
    ]
