# Generated by Django 6.0.4 on 2026-04-19 19:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
        ('fees', '0006_payment_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label to identify this structure', max_length=200),
        ),
        migrations.CreateModel(
            name='FeeStructureBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Structure Name')),
                ('due_date', models.DateField(help_text='Default due date for tuition instalments')),
                ('entrance_exam_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Grade Level Entrance Exam Fee (SAR)')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Registration Fee (SAR)')),
                ('gross_tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Total Tuition Fee (SAR)')),
                ('group_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount % on gross tuition (e.g. 10 for 10%)', max_digits=5, verbose_name='Group Discount (%)')),
                ('installments_count', models.PositiveSmallIntegerField(choices=[(1, 'Full Payment (no installments)'), (2, '2 Installments'), (3, '3 Installments'), (4, '4 Installments')], default=2, verbose_name='Number of Instalments')),
                ('min_down_payment', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Required first payment — must be greater than 0', max_digits=10, verbose_name='Minimum Down Payment (SAR)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_bundles', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles_created', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_bundles', to='core.division')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_bundles', to='core.grade')),
            ],
            options={
                'verbose_name': 'Fee Structure Bundle',
                'ordering': ['division__name', 'grade__order', 'grade__name'],
                'unique_together': {('academic_year', 'division', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='BundleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.feestructurebundle')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('bundle', 'installment_no')},
            },
        ),
    ]
