# Generated by Django 6.0.4 on 2026-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_feestructure_grade_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label, e.g. "Grade 1 American 2026-27"', max_length=200),
        ),
        migrations.AlterField(
            model_name='feestructureitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card / بطاقة ائتمانية'), ('BANK', 'Bank Transfer / تحويل بنكي'), ('INSTALLMENT', 'Installment / تقسيط')], default='CREDIT_CARD', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base amount (set at assignment time)', max_digits=10),
        ),
    ]
