# Generated by Django 6.0.4 on 2026-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_payment_mode_credit_bank_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default price pre-filled when adding this fee to a structure (not used for Tuition).', max_digits=10, null=True),
        ),
    ]
