# Generated by Django 6.0.4 on 2026-04-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_feetype_default_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Auto-selected in every fee structure (cannot be unchecked)'),
        ),
    ]
