# Generated by Django 6.0.4 on 2026-04-27 00:09

from django.db import migrations

MANDATORY_CATEGORIES = ['ENTRANCE_EXAM', 'REGISTRATION', 'TUITION', 'BOOKS']

def mark_mandatory(apps, schema_editor):
    FeeType = apps.get_model('fees', 'FeeType')
    FeeType.objects.filter(category__in=MANDATORY_CATEGORIES).update(is_mandatory=True)

def unmark_mandatory(apps, schema_editor):
    FeeType = apps.get_model('fees', 'FeeType')
    FeeType.objects.filter(category__in=MANDATORY_CATEGORIES).update(is_mandatory=False)


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_add_feetype_is_mandatory'),
    ]

    operations = [
        migrations.RunPython(mark_mandatory, reverse_code=unmark_mandatory),
    ]
