# Generated by Django 6.0.4 on 2026-04-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0015_mark_mandatory_fee_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='fixed_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this amount is always required as the minimum down payment for this fee type.', max_digits=10, null=True, verbose_name='Fixed Down Payment (SAR)'),
        ),
    ]
