# Generated by Django 6.0.4 on 2026-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_add_feetype_fixed_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='min_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required first payment when collecting fees under this structure.', max_digits=10, null=True, verbose_name='Minimum Down Payment (SAR)'),
        ),
    ]
