# Generated by Django 6.0.4 on 2026-04-27 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_add_feestructure_min_down_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='min_down_payment',
        ),
        migrations.RemoveField(
            model_name='feestructurebundle',
            name='due_date',
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='due_date_down',
            field=models.DateField(default=datetime.date(2026, 9, 1), help_text='Due date for Down Payment (Reservation)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='due_date_inst1',
            field=models.DateField(default=datetime.date(2026, 10, 1), help_text='Due date for 1st Instalment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='due_date_inst2',
            field=models.DateField(default=datetime.date(2027, 2, 1), help_text='Due date for 2nd Instalment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='due_date_inst3',
            field=models.DateField(default=datetime.date(2027, 5, 1), help_text='Due date for 3rd Instalment'),
            preserve_default=False,
        ),
    ]
