# Generated by Django 6.0.4 on 2026-04-27 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0018_replace_due_date_with_four_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructurebundle',
            name='due_date_down',
        ),
        migrations.RemoveField(
            model_name='feestructurebundle',
            name='due_date_inst1',
        ),
        migrations.RemoveField(
            model_name='feestructurebundle',
            name='due_date_inst2',
        ),
        migrations.RemoveField(
            model_name='feestructurebundle',
            name='due_date_inst3',
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 9, 1), help_text='Default due date for tuition instalments'),
            preserve_default=False,
        ),
    ]
