# Generated by Django 6.0.4 on 2026-04-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
        ('fees', '0019_revert_to_single_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructurebundle',
            options={'ordering': ['division__name', 'grade__order', 'grade__name', 'structure_type'], 'verbose_name': 'Fee Structure Bundle'},
        ),
        migrations.AlterUniqueTogether(
            name='feestructurebundle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructurebundle',
            name='structure_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('new', 'New')], default='regular', help_text='"Regular" for returning students, "New" for new admissions', max_length=20, verbose_name='Structure Type'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructurebundle',
            unique_together={('academic_year', 'division', 'grade', 'structure_type')},
        ),
    ]
