# Generated by Django 6.0.4 on 2026-04-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_add_structure_type_to_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructurebundle',
            name='code',
            field=models.CharField(blank=True, help_text='Short code for this structure, e.g. AM-REG-2526', max_length=50, verbose_name='Structure Code'),
        ),
    ]
