# Generated by Django 6.0.4 on 2026-04-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_add_code_to_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='credit_note_reason',
            field=models.TextField(blank=True, help_text='Reason for issuing credit note.'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, help_text='The original invoice this credit note refers to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='fees.taxinvoice'),
        ),
    ]
