# Generated by Django 6.0.4 on 2026-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
        ('fees', '0023_remove_fee_structure_bundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['academic_year', 'grade__division__name', 'grade__order', 'grade__name', 'structure_type']},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='structure_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('new', 'New')], default='regular', help_text='"Regular" for returning students, "New" for new admissions', max_length=20, verbose_name='Structure Type'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'grade', 'structure_type')},
        ),
    ]
