# Generated by Django 6.0.4 on 2026-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_add_structure_type_to_feestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='structure_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('new', 'New'), ('other', 'Other')], default='regular', help_text='"Regular" for returning students, "New" for new admissions', max_length=20, verbose_name='Structure Type'),
        ),
    ]
