# Generated by Django 6.0.4 on 2026-05-03 04:50

import django.db.models.deletion
import django.utils.timezone
import fees.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
        ('fees', '0025_add_other_structure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=fees.models._candidate_id, editable=False, max_length=30, unique=True, verbose_name='Candidate ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name (English)')),
                ('arabic_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم (عربي)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone / رقم الجوال')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality / الجنسية')),
                ('id_number', models.CharField(blank=True, help_text='National ID, Iqama, or Passport number', max_length=50, verbose_name='ID / Iqama / Passport')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_candidates_created', to=settings.AUTH_USER_MODEL)),
                ('grade_applying', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_candidates', to='core.grade', verbose_name='Grade Applying For / الصف')),
            ],
            options={
                'verbose_name': 'External Candidate / مرشح خارجي',
                'verbose_name_plural': 'External Candidates / مرشحون خارجيون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCandidatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_description', models.CharField(max_length=200, verbose_name='Fee Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (SAR)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT Rate (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash / نقدي'), ('CREDIT_CARD', 'Credit Card / بطاقة ائتمانية'), ('BANK', 'Bank Transfer / تحويل بنكي')], default='CASH', max_length=15)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_number', models.CharField(default=fees.models._ext_receipt_number, editable=False, max_length=30, unique=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='Bank ref / cheque no.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.externalcandidate')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_payments_collected', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='ZATCA Tax Invoice generated for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_payments', to='fees.taxinvoice')),
            ],
            options={
                'verbose_name': 'External Candidate Payment',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
