# Generated by Django 6.0.4 on 2026-05-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
        ('fees', '0026_external_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcandidate',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Which board entrance exam is the candidate taking?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_candidates', to='core.division', verbose_name='Board / Entrance Exam Division'),
        ),
    ]
