# Generated by Django 6.0.4 on 2026-05-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0027_external_candidate_board'),
        ('students', '0011_alter_student_enrollment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcandidate',
            name='enrolled_student',
            field=models.OneToOneField(blank=True, help_text='Linked student record if approved and enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student'),
        ),
        migrations.AddField(
            model_name='externalcandidate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / قيد الانتظار'), ('APPROVED', 'Approved (Enrolled) / معتمد'), ('REJECTED', 'Rejected / مرفوض')], default='PENDING', max_length=15, verbose_name='Admission Status'),
        ),
    ]
