# Generated by Django 6.0.4 on 2026-05-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_board'),
        ('fees', '0028_externalcandidate_enrolled_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcandidate',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Which board entrance exam is the candidate taking?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_candidates', to='core.board', verbose_name='Board / Entrance Exam'),
        ),
    ]
