# Generated by Django 6.0.4 on 2026-05-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_board'),
        ('fees', '0029_alter_externalcandidate_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcandidate',
            name='division',
            field=models.ForeignKey(blank=True, help_text='School division (American, British, French, Home Study)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_candidates', to='core.division', verbose_name='Division / القسم'),
        ),
    ]
