# Generated by Django 6.0.4 on 2026-05-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studymode'),
        ('fees', '0032_alter_feestructure_structure_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='study_mode',
            field=models.ForeignKey(blank=True, help_text='Optional. If set, only students with this Study Mode get this fee structure.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.studymode', verbose_name='Study Mode'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'grade', 'structure_type', 'study_mode')},
        ),
    ]
