# Generated by Django 6.0.4 on 2026-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0033_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='first_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
