# Generated by Django 6.0.4 on 2026-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_home_study_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CBSE, IGCSE, SAT, British Board', max_length=100, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='Short abbreviation, e.g. CBSE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Board',
                'verbose_name_plural': 'Exam Boards',
                'ordering': ['name'],
            },
        ),
    ]
