# Generated by Django 6.0.4 on 2026-05-04 08:25

from django.db import migrations


def create_default_data(apps, schema_editor):
    Division = apps.get_model('core', 'Division')
    Grade = apps.get_model('core', 'Grade')
    Section = apps.get_model('core', 'Section')

    # Define default divisions
    divisions_data = [
        ('American', 'AMERICAN'),
        ('British', 'BRITISH'),
        ('French', 'FRENCH'),
        ('Home Study', 'HOME_STUDY'),
    ]

    # Define default grades
    grades_data = [
        ('Nursery', 0),
        ('KG 1', 1),
        ('KG 2', 2),
        ('Grade 1', 3),
        ('Grade 2', 4),
        ('Grade 3', 5),
        ('Grade 4', 6),
        ('Grade 5', 7),
        ('Grade 6', 8),
        ('Grade 7', 9),
        ('Grade 8', 10),
        ('Grade 9', 11),
        ('Grade 10', 12),
        ('Grade 11', 13),
        ('Grade 12', 14),
    ]

    # Define default sections
    sections_data = ['A', 'B', 'C']

    # Create divisions and their grades and sections
    for div_name, curriculum_type in divisions_data:
        division, created = Division.objects.get_or_create(
            name=div_name,
            defaults={'curriculum_type': curriculum_type}
        )

        # Create grades for this division
        for grade_name, order in grades_data:
            grade, grade_created = Grade.objects.get_or_create(
                name=grade_name,
                division=division,
                defaults={'order': order}
            )

            # Create sections for this grade
            for section_name in sections_data:
                Section.objects.get_or_create(
                    name=section_name,
                    grade=grade,
                    defaults={'capacity': 30}
                )


def reverse_default_data(apps, schema_editor):
    Division = apps.get_model('core', 'Division')
    Division.objects.filter(name__in=['American', 'British', 'French', 'Home Study']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_division_name'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse_default_data),
    ]
