# Generated by Django 6.0.4 on 2026-05-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_default_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Home Study, Distance Study, Hybrid', max_length=100, unique=True)),
                ('arabic_name', models.CharField(blank=True, help_text='e.g. الدراسة المنزلية', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Mode',
                'verbose_name_plural': 'Study Modes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
